### ISSUE TITLE
php_mycrypt won't install on CentOs

### ISSUE THREAD

**Issue by ToonMeynen** [alexggolovin/alexggolovin-opencart#1]
I'm using Centos6.4.

**Comment by alexggolovin** [comment]
What CentOS version, any changes on default module confiugrations been done? just to be clear.

**Comment by ToonMeynen** [comment]
I modified servers.pp. To get it working. 
mysql::db { $mydb:
        user          => "${mydb}",
        password      => "${mypass}",
        host          => 'localhost',
    }

**Comment by ToonMeynen** [comment]
I installed an epel module from the forge. Because php_mcrypt is not in the default repository.

**Comment by alexggolovin** [comment]
Thanks for that note, I'll update README file, the EPEL must be added on both RedHat and CentOS distributions.

**Comment by alexggolovin** [comment]
Please let me know, did it works with EPEL added properly?

**Comment by ToonMeynen** [comment]
Yes I installed https://forge.puppetlabs.com/stahnma/epel https://forge.puppetlabs.com/stahnma/epel on the node. And it worked like a charm. I would include this as a dependency for the RHEL family.

**Comment by alexggolovin** [comment]
Today I just checked on CentOS-6, looks like all works well, now seems what we need that's only EPEL to be added as installed dependency in case of CentOS or RedHat.

**Comment by alexggolovin** [comment]
ToonMeynen, 
I just released 1.1.2 version, uploaded to puppet forge. The epel repository added as dependency for RedHat and CentOS, see Changelog and README.md files for details. Tested on CentOS release 6.6 (Final) distribution, seems like works well. Please double check that's ok and let me know when issue can be closed.

Thanks,

**Comment by alexggolovin** [comment]
Fixed in 1.1.3 release, stahnma-epel module added as dependency for CentOS/RedHat distributions components from EPEL repository.
